environment:
  node_pre_gyp_accessKeyId:
    secure: p2BcCi3HR3SnrUwqzFHbJK3slT4FGBc+F9iRy7a6Los=
  node_pre_gyp_secretAccessKey:
    secure: 6C95HM2rlmtHtyp0FwOH/cjxViVNA3RuAJMh9S/xOyREiBfo8TPFrTTFM1+BmW2l
  node_pre_gyp_region: eu-central-1
  matrix:
    - nodejs_version: "5.8.0"

platform:
  - x64

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: Install-Product node $env:nodejs_version
  - node -v
  - npm install -g npm
  - npm install

test_script:
  - npm test

build: off
deploy: off

on_success:
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains('v1.2.3')) { $env: --msvs_version=2013 package }
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains('v1.2.3')) { node node_modules\node-pre-gyp\bin\node-pre-gyp --msvs_version=2013 package }
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains('v1.2.3')) { node node_modules\node-pre-gyp\bin\node-pre-gyp --msvs_version=2013 publish }

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))